# Basics of TensorFlow

#### This tutorial covers the following contents

* The "Hello Zeke"
* Graphs
* Session
* Fetches
* DataType
* Tensor Sequences
* Variables
* Placeholders

<hr style="height:2px;border:none;">

### Import & version check

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.4.0'

### Hello World in TensorFlow
* h, w & hw are nodes of graph.
* run() will execute the graph

In [3]:
h = tf.constant("Hello")

In [4]:
w = tf.constant("Zeke")

In [5]:
hw = h + w

In [6]:
hw

<tf.Tensor 'add:0' shape=() dtype=string>

In [7]:
with tf.Session() as sess:
    res = sess.run(hw)
    tf.summary.FileWriter('tensorboard/new-logs',sess.graph)

<img src="https://github.com/zekelabs/tensorflow-tutorial/blob/master/graph1.png?raw=true">

In [8]:
res

b'HelloZeke'

### Graphs, Sessions & Fetches

In [9]:
a = tf.constant(5)
b = tf.constant(7)
c = tf.constant(10)

In [10]:
d = tf.multiply(a,b)
e = tf.add(b,c)
f = tf.subtract(d,e)

In [11]:
with tf.Session() as sess:
    out = sess.run(f)

In [12]:
out

18

In [13]:
tf.get_default_graph()

In [14]:
g = tf.Graph()

In [15]:
g

In [16]:
a = tf.constant(5)

In [17]:
a.graph is tf.get_default_graph()

True

In [18]:
with g.as_default():
    a = tf.constant(77)
    print (a.graph)

### Fetches 

In [19]:
a = tf.constant(5)
b = tf.constant(7)
c = tf.constant(10)
d = tf.multiply(a,b)
e = tf.add(b,c)
f = tf.subtract(d,e)
with tf.Session() as sess:
    out = sess.run(f)

In [20]:
with tf.Session() as sess:
    fetches = [a,b,c,d,e,f]
    outs = sess.run(fetches)

print(outs)

[5, 7, 10, 35, 17, 18]


### Data Types

In [21]:
c = tf.constant(4.0, dtype=tf.float64)

In [22]:
d = tf.cast(c,tf.float16)

In [23]:
d.dtype

tf.float16

### Tensor Arrays & Shapes

In [24]:
c = tf.constant( [[1,2,3],[4,5,6]])

In [25]:
import numpy as np

In [26]:
d = np.array([ [1,2,3], [4,5,6]])

In [27]:
tf.constant(d)

<tf.Tensor 'Const_11:0' shape=(2, 3) dtype=int32>

In [28]:
d = tf.linspace(start=2.0,stop=10.0, num=20)

In [29]:
with tf.Session() as sess:
    o = sess.run(d)

In [30]:
o

array([  2.        ,   2.42105269,   2.84210539,   3.26315784,
         3.68421054,   4.10526323,   4.52631569,   4.94736862,
         5.36842108,   5.78947353,   6.21052647,   6.63157892,
         7.05263138,   7.47368431,   7.89473677,   8.31579018,
         8.73684216,   9.15789413,   9.57894707,  10.        ], dtype=float32)

In [31]:
s = tf.fill((4,5),100)

In [32]:
with tf.Session() as sess:
    o = sess.run(s)
    print (o.shape)

(4, 5)


In [33]:
o

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [34]:
A = tf.constant( [
                   [1,2,3],
                   [4,5,6]
                 ])

In [35]:
b = tf.constant( [1,0,1])

In [36]:
b = tf.expand_dims(b,1)

In [37]:
b.shape

TensorShape([Dimension(3), Dimension(1)])

In [38]:
A.shape

TensorShape([Dimension(2), Dimension(3)])

In [39]:
matmul = tf.matmul(A,b)

In [40]:
with tf.Session() as sess:
    o = sess.run(matmul)
    print (sess.run(b))

[[1]
 [0]
 [1]]


In [41]:
o

array([[ 4],
       [10]])

In [42]:
with tf.Session() as sess:
    fetches = [A,b]
    outs = sess.run(fetches)

In [43]:
outs

[array([[1, 2, 3],
        [4, 5, 6]]), array([[1],
        [0],
        [1]])]

In [44]:
r = tf.transpose(A)

In [45]:
with tf.Session() as sess:
    fetches = [r]
    outs = sess.run(fetches)

In [46]:
outs

[array([[1, 4],
        [2, 5],
        [3, 6]])]

### Variables & Placeholders

In [47]:
init_vals = tf.random_normal((1,5),0,1)

In [48]:
init_vals.shape

TensorShape([Dimension(1), Dimension(5)])

In [49]:
var = tf.Variable(init_vals)

In [50]:
init = tf.global_variables_initializer()

In [51]:
with tf.Session() as sess:
    sess.run(init)
    print ( sess.run(var))

[[ 0.96715963  0.4355787   0.82825756 -2.15556312 -0.44612083]]


### Placeholders 

In [52]:
ph = tf.placeholder(tf.int16)

In [53]:
d = tf.multiply(ph,2)
    

In [54]:
with tf.Session() as sess:
    print(sess.run(d, feed_dict={ph:5}))
    print(sess.run(d, feed_dict={ph:15}))

10
30
